engines:
        sonar-java:
                        enabled: true
                exclude_paths:
                - "**.js"     


#ratings:
#   paths:
#   - "src/**.java"

#exclude_paths:
#- "**.js"
